defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11
version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"
  install:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Yarn install"
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "List"
          command: ls -la
      - run:
          name: "Test"
          command: npm run test
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Build app"
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json
  deploy:
    <<: *defaults
    environment:
      - STAGING_BUCKET: YOUR_STAGING_BUCKET_NAME
      - PRODUCTION_BUCKET: YOUR_PRODUCTION_BUCKET_NAME
      - STAGING_DISTRIBUTION_ID: YOUR_STAGING_DISTRIBUTION_ID
      - PRODUCTION_DISTRIBUTION_ID: YOUR_PRODUCTION_DISTRIBUTION_ID
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "Ready to deploy"
      - run: ls -al

      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
      - run: aws s3 ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - test
            - build
