version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    working_directory: ~/koodarinpalkka
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: npm test -- --coverage
      - run:
          name: Build
          command: npm run build
      - aws-s3/sync:
          from: build
          to: "s3://koodarinpalkka.fi"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
