jobs:
  build:
    working_directory: ~/project

    executor:
      name: node/default
      tag: "14.15.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  deploy:
    working_directory: ~/project
    docker:
      - image: "cimg/python:3.6"
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls -alh
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./build
          overwrite: true
          to: "s3://${CLIENT_BUCKET}"
      - run:
          name: Invalidate CloudFront Cache
          command: >
            aws cloudfront create-invalidation --distribution-id ${CLIENT_DISTRIBUTION} --paths "/*"
      - slack/status:
          success_message: ":tada: Uusi versio on julkaistu -> $CLIENT_BUCKET"

orbs:
  aws-s3: circleci/aws-s3@1.0.15
  node: circleci/node@2.1.1
  slack: circleci/slack@3.4.2
version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
